# Array operation

In [6]:
import numpy as np
import math
a =np.array(range(5))
print ('a=',a)

b =np.array(range(3,9,2))
print('b=',b)
       
#better use arange

a1 =np.arange(1,6)
print ('a1=',a1)
c=np.arange(1,10,0.5)
print('c=',c, '  c.shape=', c.shape)
print('len=',len(c))

#c.len
print('siz=',c.size)


print('a1 type is', type(a1))
range1 = range(1,16,2)
print('range1 type is', type(range1))
print (range1)
for i in range1: print(i,end =',')

a= [0 1 2 3 4]
b= [3 5 7]
a1= [1 2 3 4 5]
c= [ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.
  8.5  9.   9.5]   c.shape= (18,)
len= 18
siz= 18
a1 type is <class 'numpy.ndarray'>
range1 type is <class 'range'>
range(1, 16, 2)
1,3,5,7,9,11,13,15,

In [8]:
#comparison
ab = (a==a1)
print(ab)
aa = (a==a)
print(aa)



#array wise comparison
ab_=np.array_equal(a, b)
print(ab_)
aa_=np.array_equal(a,a )
print(aa_)

[False False False False False]
[ True  True  True  True  True]
False
True


In [15]:
ar=range(6)
print(type(ar))
#print(next(ar))
print(ar[1],ar[5])

#print(ar[i],end=',') for i in ar #does not work
for i in ar:print(ar[i],end=',')

for i in ar:
    print(ar[i],end=',')

print('')
#array_1=[i*i for for i in ar]    #error
array_1=np.array(ar)
print(type(array_1))
for i in range(len(array_1)) : print(array_1[i],end=',')

<class 'range'>
1 5
0,1,2,3,4,5,0,1,2,3,4,5,
<class 'numpy.ndarray'>
0,1,2,3,4,5,

In [17]:
# to create a list using range()
L1=list(range(1,100,10))
for i in range(len(L1)):print(L1[i],end=',')
L1

1,11,21,31,41,51,61,71,81,91,

[1, 11, 21, 31, 41, 51, 61, 71, 81, 91]

In [16]:
a=np.array([1,2,0,0],dtype=bool)
print ('a=',a)
b=np.array([1, 0, 1, 0])
print ('b=',b)
ab_or=np.logical_or(a,b)
print('ab_or=',ab_or)
ab_and=np.logical_and(a,b)
print('ab_and=',ab_and)

a= [ True  True False False]
b= [1 0 1 0]
ab_or= [ True  True  True False]
ab_and= [ True False False False]


In [18]:
# reshape
c = np.reshape(c,(3,6))
print('c=',c, '  c.shape=', c.shape)

d=np.arange(1,10,0.5).reshape(3,6)
print('d=',d, '\n d.shape=', d.shape)

c= [[ 1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5]
 [ 7.   7.5  8.   8.5  9.   9.5]]   c.shape= (3, 6)
d= [[ 1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5]
 [ 7.   7.5  8.   8.5  9.   9.5]] 
 d.shape= (3, 6)


In [20]:
g1=np.sin(c)
print('g1=',g1, '\n g1.shape=', g1.shape)
g10 =g1*g1
g10


g1= [[ 0.84147098  0.99749499  0.90929743  0.59847214  0.14112001 -0.35078323]
 [-0.7568025  -0.97753012 -0.95892427 -0.70554033 -0.2794155   0.21511999]
 [ 0.6569866   0.93799998  0.98935825  0.79848711  0.41211849 -0.07515112]] 
 g1.shape= (3, 6)


array([[ 0.70807342,  0.99499625,  0.82682181,  0.35816891,  0.01991486,
         0.12304887],
       [ 0.57275002,  0.95556513,  0.91953576,  0.49778715,  0.07807302,
         0.04627661],
       [ 0.43163139,  0.87984396,  0.97882974,  0.63758167,  0.16984165,
         0.00564769]])

In [21]:
f= (np.sin(c))**2 +(np.cos(c))**2
print('f=',f, '  f.shape=', f.shape)

f= [[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]   f.shape= (3, 6)


In [30]:
print(c.sum(),c.mean(),c.max(),len(c),c.shape)

94.5 5.25 9.5 3 (3, 6)


In [31]:
f.sum()

18.0

In [36]:
c**2

array([[  1.  ,   2.25,   4.  ,   6.25,   9.  ,  12.25],
       [ 16.  ,  20.25,  25.  ,  30.25,  36.  ,  42.25],
       [ 49.  ,  56.25,  64.  ,  72.25,  81.  ,  90.25]])

In [44]:
print(c)

print('c[0]=',c[0])
print('c[2]=',c[2])
print(c[0].sum())
print(c[2].sum())

print('c[:0]=',c[:0])
print('c[:2]=',c[:2])

print(c[:0].sum())
print(c[:2].sum())

print('c[:,0]=',c[:,0])
print('c[:,2]=',c[:,2])

print('c[:,4:6]=',c[:,4:6])
print('c[0:2,:]=',c[0:2,])

print('c.sum()=',c.sum())


[[ 1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5]
 [ 7.   7.5  8.   8.5  9.   9.5]]
c[0]= [ 1.   1.5  2.   2.5  3.   3.5]
c[2]= [ 7.   7.5  8.   8.5  9.   9.5]
13.5
49.5
c[:0]= []
c[:2]= [[ 1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5]]
0.0
45.0
c[:,0]= [ 1.  4.  7.]
c[:,2]= [ 2.  5.  8.]
c[:,4:6]= [[ 3.   3.5]
 [ 6.   6.5]
 [ 9.   9.5]]
c[0:2,:]= [[ 1.   1.5  2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5  6.   6.5]]
c.sum()= 94.5


In [46]:
g1

array([ 0.84147098,  0.99749499,  0.90929743,  0.59847214,  0.14112001,
       -0.35078323, -0.7568025 , -0.97753012, -0.95892427, -0.70554033,
       -0.2794155 ,  0.21511999,  0.6569866 ,  0.93799998,  0.98935825,
        0.79848711,  0.41211849, -0.07515112])

In [51]:
(g1**5).sum()

2.1077561907141753